version: '3.8'
services:
  app:
    image: imagegallery
    build:
      context: .
      dockerfile: DockerFile
    volumes:
      - images:/app/images  # Mount for images
      - thumbnails:/app/thumbnails  # Mount for thumbnails
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgresdb
      SPRING_DATASOURCE_USERNAME: van
      SPRING_DATASOURCE_PASSWORD: mops294
      SPRING_JPA_HIBERNATE_DDL_AUTO: update


  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgresdb
      POSTGRES_USER: van
      POSTGRES_PASSWORD: mops294
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  images: {}
  thumbnails: {}